# This is a basic workflow to help you get started with Actions

name: gradle CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: study-app-server
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: JDK 11 설치
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: ./gradlew 권한 설정
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew build

      - name: aws 세팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 업로드
        run: aws deploy push --application-name study-app-codedeploy-server --description "study-app server" --s3-location s3://g-s3-c/archive/build.zip --source .

      - name: code deploy
        run: aws deploy create-deployment --application-name study-app-codedeploy-server --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=g-s3-c,bundleType=zip,key=server/build.zip
